import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  default: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction to Kubernetes Security',
    },
    {
      type: 'category',
      label: 'Fundamentals',
      link: { type: 'doc', id: 'fundamentals/intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Attack Vectors',
      link: { type: 'doc', id: 'attack_vectors/intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'attack_vectors',
        },
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      link: { type: 'doc', id: 'best_practices/intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'best_practices',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      link: { type: 'doc', id: 'tools/intro' },
      items: [], // You can add autogenerated or manual items here as needed
    },
  ],
};

export default sidebars;

