// sidebarItemsGenerator.js
const defaultGenerator = require('@docusaurus/plugin-content-docs/lib/sidebars/generators/autogenerated');

module.exports = async function filteredSidebarItemsGenerator(args) {
  const sidebarItems = await defaultGenerator(args);

  function filterIntro(items) {
    return items
      .map(item => {
        if (item.type === 'category') {
          return {
            ...item,
            items: filterIntro(item.items),
          };
        }
        if (item.type === 'doc' && item.id.endsWith('/intro')) {
          return null; // exclude intros
        }
        return item;
      })
      .filter(Boolean);
  }

  return filterIntro(sidebarItems);
};
