/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Automatically generate sidebar from the filesystem for the "Guides" section
  guidesSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;

